# These are supported funding model platforms

github: [lnavarrocarter]
patreon: nachonavarro
open_collective: 
ko_fi: nachonavarro
tidelift: 
community_bridge: 
liberapay: nachonavarro
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: nachonavarro
thanks_dev: 
custom: ['https://paypal.me/lnavarrocarter', 'https://www.buymeacoffee.com/nachonavarro']

